// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/server/server.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	maintainer "github.com/pingcap/ticdc/maintainer"
	etcd "github.com/pingcap/ticdc/pkg/etcd"
	liveness "github.com/pingcap/ticdc/pkg/liveness"
	node "github.com/pingcap/ticdc/pkg/node"
	server "github.com/pingcap/ticdc/pkg/server"
	pd "github.com/tikv/pd/client"
)

// MockServer is a mock of Server interface.
type MockServer struct {
	ctrl     *gomock.Controller
	recorder *MockServerMockRecorder
}

// MockServerMockRecorder is the mock recorder for MockServer.
type MockServerMockRecorder struct {
	mock *MockServer
}

// NewMockServer creates a new mock instance.
func NewMockServer(ctrl *gomock.Controller) *MockServer {
	mock := &MockServer{ctrl: ctrl}
	mock.recorder = &MockServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServer) EXPECT() *MockServerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockServer) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockServerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockServer)(nil).Close))
}

// GetCoordinator mocks base method.
func (m *MockServer) GetCoordinator() (server.Coordinator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCoordinator")
	ret0, _ := ret[0].(server.Coordinator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCoordinator indicates an expected call of GetCoordinator.
func (mr *MockServerMockRecorder) GetCoordinator() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCoordinator", reflect.TypeOf((*MockServer)(nil).GetCoordinator))
}

// GetCoordinatorInfo mocks base method.
func (m *MockServer) GetCoordinatorInfo(ctx context.Context) (*node.Info, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCoordinatorInfo", ctx)
	ret0, _ := ret[0].(*node.Info)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCoordinatorInfo indicates an expected call of GetCoordinatorInfo.
func (mr *MockServerMockRecorder) GetCoordinatorInfo(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCoordinatorInfo", reflect.TypeOf((*MockServer)(nil).GetCoordinatorInfo), ctx)
}

// GetEtcdClient mocks base method.
func (m *MockServer) GetEtcdClient() etcd.CDCEtcdClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEtcdClient")
	ret0, _ := ret[0].(etcd.CDCEtcdClient)
	return ret0
}

// GetEtcdClient indicates an expected call of GetEtcdClient.
func (mr *MockServerMockRecorder) GetEtcdClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEtcdClient", reflect.TypeOf((*MockServer)(nil).GetEtcdClient))
}

// GetMaintainerManager mocks base method.
func (m *MockServer) GetMaintainerManager() *maintainer.Manager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaintainerManager")
	ret0, _ := ret[0].(*maintainer.Manager)
	return ret0
}

// GetMaintainerManager indicates an expected call of GetMaintainerManager.
func (mr *MockServerMockRecorder) GetMaintainerManager() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaintainerManager", reflect.TypeOf((*MockServer)(nil).GetMaintainerManager))
}

// GetPdClient mocks base method.
func (m *MockServer) GetPdClient() pd.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPdClient")
	ret0, _ := ret[0].(pd.Client)
	return ret0
}

// GetPdClient indicates an expected call of GetPdClient.
func (mr *MockServerMockRecorder) GetPdClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPdClient", reflect.TypeOf((*MockServer)(nil).GetPdClient))
}

// IsCoordinator mocks base method.
func (m *MockServer) IsCoordinator() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCoordinator")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsCoordinator indicates an expected call of IsCoordinator.
func (mr *MockServerMockRecorder) IsCoordinator() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCoordinator", reflect.TypeOf((*MockServer)(nil).IsCoordinator))
}

// Liveness mocks base method.
func (m *MockServer) Liveness() liveness.Liveness {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Liveness")
	ret0, _ := ret[0].(liveness.Liveness)
	return ret0
}

// Liveness indicates an expected call of Liveness.
func (mr *MockServerMockRecorder) Liveness() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Liveness", reflect.TypeOf((*MockServer)(nil).Liveness))
}

// Run mocks base method.
func (m *MockServer) Run(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockServerMockRecorder) Run(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockServer)(nil).Run), ctx)
}

// SelfInfo mocks base method.
func (m *MockServer) SelfInfo() (*node.Info, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelfInfo")
	ret0, _ := ret[0].(*node.Info)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelfInfo indicates an expected call of SelfInfo.
func (mr *MockServerMockRecorder) SelfInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelfInfo", reflect.TypeOf((*MockServer)(nil).SelfInfo))
}
