// Code generated by MockGen. DO NOT EDIT.
// Source: downstreamadapter/sink/sink.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	common "github.com/pingcap/ticdc/pkg/common"
	event "github.com/pingcap/ticdc/pkg/common/event"
)

// MockSink is a mock of Sink interface.
type MockSink struct {
	ctrl     *gomock.Controller
	recorder *MockSinkMockRecorder
}

// MockSinkMockRecorder is the mock recorder for MockSink.
type MockSinkMockRecorder struct {
	mock *MockSink
}

// NewMockSink creates a new mock instance.
func NewMockSink(ctrl *gomock.Controller) *MockSink {
	mock := &MockSink{ctrl: ctrl}
	mock.recorder = &MockSinkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSink) EXPECT() *MockSinkMockRecorder {
	return m.recorder
}

// AddCheckpointTs mocks base method.
func (m *MockSink) AddCheckpointTs(ts uint64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddCheckpointTs", ts)
}

// AddCheckpointTs indicates an expected call of AddCheckpointTs.
func (mr *MockSinkMockRecorder) AddCheckpointTs(ts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCheckpointTs", reflect.TypeOf((*MockSink)(nil).AddCheckpointTs), ts)
}

// AddDMLEvent mocks base method.
func (m *MockSink) AddDMLEvent(event *event.DMLEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddDMLEvent", event)
}

// AddDMLEvent indicates an expected call of AddDMLEvent.
func (mr *MockSinkMockRecorder) AddDMLEvent(event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDMLEvent", reflect.TypeOf((*MockSink)(nil).AddDMLEvent), event)
}

// BatchBytes mocks base method.
func (m *MockSink) BatchBytes() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchBytes")
	ret0, _ := ret[0].(int)
	return ret0
}

// BatchBytes indicates an expected call of BatchBytes.
func (mr *MockSinkMockRecorder) BatchBytes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchBytes", reflect.TypeOf((*MockSink)(nil).BatchBytes))
}

// BatchCount mocks base method.
func (m *MockSink) BatchCount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCount")
	ret0, _ := ret[0].(int)
	return ret0
}

// BatchCount indicates an expected call of BatchCount.
func (mr *MockSinkMockRecorder) BatchCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCount", reflect.TypeOf((*MockSink)(nil).BatchCount))
}

// Close mocks base method.
func (m *MockSink) Close(removeChangefeed bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close", removeChangefeed)
}

// Close indicates an expected call of Close.
func (mr *MockSinkMockRecorder) Close(removeChangefeed interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSink)(nil).Close), removeChangefeed)
}

// FlushDMLBeforeBlock mocks base method.
func (m *MockSink) FlushDMLBeforeBlock(event event.BlockEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FlushDMLBeforeBlock", event)
	ret0, _ := ret[0].(error)
	return ret0
}

// FlushDMLBeforeBlock indicates an expected call of FlushDMLBeforeBlock.
func (mr *MockSinkMockRecorder) FlushDMLBeforeBlock(event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FlushDMLBeforeBlock", reflect.TypeOf((*MockSink)(nil).FlushDMLBeforeBlock), event)
}

// IsNormal mocks base method.
func (m *MockSink) IsNormal() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsNormal")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsNormal indicates an expected call of IsNormal.
func (mr *MockSinkMockRecorder) IsNormal() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsNormal", reflect.TypeOf((*MockSink)(nil).IsNormal))
}

// Run mocks base method.
func (m *MockSink) Run(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockSinkMockRecorder) Run(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockSink)(nil).Run), ctx)
}

// SetTableSchemaStore mocks base method.
func (m *MockSink) SetTableSchemaStore(tableSchemaStore *event.TableSchemaStore) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTableSchemaStore", tableSchemaStore)
}

// SetTableSchemaStore indicates an expected call of SetTableSchemaStore.
func (mr *MockSinkMockRecorder) SetTableSchemaStore(tableSchemaStore interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTableSchemaStore", reflect.TypeOf((*MockSink)(nil).SetTableSchemaStore), tableSchemaStore)
}

// SinkType mocks base method.
func (m *MockSink) SinkType() common.SinkType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SinkType")
	ret0, _ := ret[0].(common.SinkType)
	return ret0
}

// SinkType indicates an expected call of SinkType.
func (mr *MockSinkMockRecorder) SinkType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SinkType", reflect.TypeOf((*MockSink)(nil).SinkType))
}

// WriteBlockEvent mocks base method.
func (m *MockSink) WriteBlockEvent(event event.BlockEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteBlockEvent", event)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteBlockEvent indicates an expected call of WriteBlockEvent.
func (mr *MockSinkMockRecorder) WriteBlockEvent(event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteBlockEvent", reflect.TypeOf((*MockSink)(nil).WriteBlockEvent), event)
}
