#!/usr/bin/env bash

changefeed_id=""
pd=""

while [ $# -ne 0 ]; do
	case "$1" in
	--changefeed-id=*)
		changefeed_id="${1#*=}"
		;;
	--pd=*)
		# We don't use pd when using TiCDC api
		# pd="${1#*=}"
		;;
	*)
		echo "Unknown option: $1"
		exit 1
		;;
	esac
	shift
done

if [ -z "$changefeed_id" ]; then
	echo "changefeed_id is required" >&2
	exit 1
fi

curl -X POST "http://$CDC_DEFAULT_HOST:$CDC_DEFAULT_PORT/api/v2/changefeeds/$changefeed_id/pause"
