#!/usr/bin/env bash

if [ $# -lt 1 ]; then
	echo "Usage: psutil <process>"
	exit 1
fi

os=$(uname -s)
pid=
if [[ "$os" == "Darwin" ]]; then
	pid=$(pgrep -f "run_cdc_server" | head -n 1)
else
	pid=$(ps -C run_cdc_server -o pid= | tr -d '[:space:]')
fi
echo $pid
