#!/bin/bash

# cdc server is ran by binary cdc.test, kill cdc server first to avoid too much
# noise in cdc logs.

PKILL="killall -q -w -s 9 "
if [ "$(uname)" == "Darwin" ]; then
	PKILL="pkill -9 "
fi

${PKILL} cdc.test || true
${PKILL} cdc || true
${PKILL} cdc_kafka_consumer || true
${PKILL} cdc_storage_consumer || true
${PKILL} tidb-server || true
${PKILL} tikv-server || true
${PKILL} tiflash || true
${PKILL} flash_cluster_manager || true
${PKILL} pd-server || true
${PKILL} oauth_server || true

CUR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
source $CUR/../_utils/test_prepare

killport() {
	if [ -z "$1" ]; then
		return 0
	fi

	pid=$(lsof -i tcp:$1 -t 2>/dev/null | tail -n1)
	if [ -z "$pid" ]; then
		return 0
	fi

	kill -9 "$pid" &>/dev/null
	return 0
}

killport "${UP_TIDB_PORT}"
killport "${UP_TIDB_OTHER_PORT}"
killport "${UP_TIDB_STATUS}"
killport "${UP_TIDB_OTHER_STATUS}"
killport "${DOWN_TIDB_PORT}"
killport "${DOWN_TIDB_STATUS}"
killport "${UP_PD_PORT_1}"
killport "${UP_PD_PEER_PORT_1}"
killport "${UP_PD_PORT_2}"
killport "${UP_PD_PEER_PORT_2}"
killport "${UP_PD_PORT_3}"
killport "${UP_PD_PEER_PORT_3}"
killport "${DOWN_PD_PORT}"
killport "${DOWN_PD_PEER_PORT}"
killport "${UP_TIKV_PORT_1}"
killport "${UP_TIKV_STATUS_PORT_1}"
killport "${UP_TIKV_PORT_2}"
killport "${UP_TIKV_STATUS_PORT_2}"
killport "${UP_TIKV_PORT_3}"
killport "${UP_TIKV_STATUS_PORT_3}"
killport "${DOWN_TIKV_PORT}"
killport "${DOWN_TIKV_STATUS_PORT}"
killport "9500"
killport "17000"
killport "6650"
killport "6651"
killport "9096"
